Resources:
  MyBucket:
    Type: !Sub '{{resolve:ssm:/arn}}'
    Parameters:
      BucketName: !Sub '{{resolve:ssm:/name}}'
  SSMNAME:
    Type: 'AWS::SSM::Parameter'
    Parameters:
      Name: !Join 
        - ''
        - - /name
      Type: String
      Value: STD21039
  SSMARN:
    Type: 'AWS::SSM::Parameter'
    Parameters:
      Name: !Join 
        - ''
        - - /arn
      Type: String
      Value: 'AWS::S3::Bucket'
