Resources:
  MyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: std21039
  SSMName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /name
      Type: String
      Value: !Ref MyBucket
  SSMArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /arn
      Type: String
      Value: !GetAtt MyBucket.Arn
