Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Parameters:
      BucketName: STD21039
  SSMNAME:
    Type: 'AWS::SSM::Parameter'
    Parameters:
      Name: /name
      Type: String
      Value: !Ref MyBucket
  SSMARN:
    Type: 'AWS::SSM::Parameter'
    Parameters:
      Name: /arn
      Type: String
      Value: !GettAt MyBucket.Arn
